default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scrummie_development
  username: <%= ENV['SCRUMMIE_USERNAME'] %>
  password: <%= ENV['SCRUMMIE_PASSWORD'] %>
  host: localhost
  port: 5433

test:
  <<: *default
  database: scrummie_test
  username: <%= ENV['SCRUMMIE_USERNAME'] %>
  password: <%= ENV['SCRUMMIE_PASSWORD'] %>
  host: localhost
  port: 5433
